### ISSUE TITLE
Import: show summary of errors

### ISSUE THREAD

**Issue by emente** [DSB/oTranCe#40]
Had an error rate of 100% when importing a file into otrance.

The reason given in the ajax-request was status:3, and only the sourcecode offerend an explanation what this code means.

It would be very nice if there is a short summary in the end-of-import dialog, like:
technical errors: 0
saved successfully: 0
user has no edit right for this language: 0
user is not allowed to add this new entry: 3840

An alternative would be to show an error to the user if the user has no right to add new keys (or no right to edit current language) when viewing the import dialog.

**Comment by DSB** [comment]
There is a summary in the top right status box telling exactly the info you are requesting.
Additionally each key gets an icon after it is processed. A green hook for success and a red icon if something went wrong. When you hover the red icon a title tag shows the reason. This is the place where the status codes are translated into meaningful text messages.

But I fully agree that at the end of the import process these infos are not presented very well because the modal popup hides that info. The funny thing is that I already wrote a ticket for that myself and started to solve this by showing such a overall result page. See ticket: https://mysqldumper.jira.com/browse/OTC-227
Maybe this is a reason for me to finish the ticket this weekend.
